// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package relation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RelationServiceClient is the client API for RelationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelationServiceClient interface {
	CreatRelation(ctx context.Context, in *CreatRelationRequest, opts ...grpc.CallOption) (*CreatRelationResponse, error)
	GetProfileFollowing(ctx context.Context, in *GetProfileFollowingRequest, opts ...grpc.CallOption) (*GetProfileFollowingResponse, error)
	GetProfileFollower(ctx context.Context, in *GetProfileFollowerRequest, opts ...grpc.CallOption) (*GetProfileFollowerResponse, error)
}

type relationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelationServiceClient(cc grpc.ClientConnInterface) RelationServiceClient {
	return &relationServiceClient{cc}
}

func (c *relationServiceClient) CreatRelation(ctx context.Context, in *CreatRelationRequest, opts ...grpc.CallOption) (*CreatRelationResponse, error) {
	out := new(CreatRelationResponse)
	err := c.cc.Invoke(ctx, "/relation.RelationService/CreatRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationServiceClient) GetProfileFollowing(ctx context.Context, in *GetProfileFollowingRequest, opts ...grpc.CallOption) (*GetProfileFollowingResponse, error) {
	out := new(GetProfileFollowingResponse)
	err := c.cc.Invoke(ctx, "/relation.RelationService/GetProfileFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationServiceClient) GetProfileFollower(ctx context.Context, in *GetProfileFollowerRequest, opts ...grpc.CallOption) (*GetProfileFollowerResponse, error) {
	out := new(GetProfileFollowerResponse)
	err := c.cc.Invoke(ctx, "/relation.RelationService/GetProfileFollower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelationServiceServer is the server API for RelationService service.
// All implementations must embed UnimplementedRelationServiceServer
// for forward compatibility
type RelationServiceServer interface {
	CreatRelation(context.Context, *CreatRelationRequest) (*CreatRelationResponse, error)
	GetProfileFollowing(context.Context, *GetProfileFollowingRequest) (*GetProfileFollowingResponse, error)
	GetProfileFollower(context.Context, *GetProfileFollowerRequest) (*GetProfileFollowerResponse, error)
	mustEmbedUnimplementedRelationServiceServer()
}

// UnimplementedRelationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRelationServiceServer struct {
}

func (UnimplementedRelationServiceServer) CreatRelation(context.Context, *CreatRelationRequest) (*CreatRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatRelation not implemented")
}
func (UnimplementedRelationServiceServer) GetProfileFollowing(context.Context, *GetProfileFollowingRequest) (*GetProfileFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileFollowing not implemented")
}
func (UnimplementedRelationServiceServer) GetProfileFollower(context.Context, *GetProfileFollowerRequest) (*GetProfileFollowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileFollower not implemented")
}
func (UnimplementedRelationServiceServer) mustEmbedUnimplementedRelationServiceServer() {}

// UnsafeRelationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelationServiceServer will
// result in compilation errors.
type UnsafeRelationServiceServer interface {
	mustEmbedUnimplementedRelationServiceServer()
}

func RegisterRelationServiceServer(s grpc.ServiceRegistrar, srv RelationServiceServer) {
	s.RegisterService(&RelationService_ServiceDesc, srv)
}

func _RelationService_CreatRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).CreatRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationService/CreatRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).CreatRelation(ctx, req.(*CreatRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationService_GetProfileFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).GetProfileFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationService/GetProfileFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).GetProfileFollowing(ctx, req.(*GetProfileFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationService_GetProfileFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileFollowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServiceServer).GetProfileFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationService/GetProfileFollower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServiceServer).GetProfileFollower(ctx, req.(*GetProfileFollowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelationService_ServiceDesc is the grpc.ServiceDesc for RelationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relation.RelationService",
	HandlerType: (*RelationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatRelation",
			Handler:    _RelationService_CreatRelation_Handler,
		},
		{
			MethodName: "GetProfileFollowing",
			Handler:    _RelationService_GetProfileFollowing_Handler,
		},
		{
			MethodName: "GetProfileFollower",
			Handler:    _RelationService_GetProfileFollower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relation.proto",
}
